version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_system_dependencies.sh
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: www-data
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
