version: 0.0
os: linux
# files:
#   - source: /
#     destination: /var/www/html
  
hooks:
  ApplicationStop:
    - location: scripts/hello.sh
      timeout: 5
      runas: root
  # BeforeInstall:
  #   - location: scripts/hello.sh
  #     timeout: 100
  #     runas: root
  # AfterInstall:
  #   - location: scripts/hello.sh
  #     timeout: 100
  #     runas: root
  # ApplicationStart:
  #   - location: scripts/hello.sh
  #     timeout: 5
  #     runas: root
  
