version: 0.2

run-as: www-data

# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes

batch:
  fast-fail: false
  # build-list:
  # build-matrix:
  # build-graph:
  # build-fanout:
        
phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      php: 8.3
    commands:
      - chmod +x ./scripts/install_dependencies.sh
      - sh ./scripts/install_dependencies.sh
      # - echo "hello"
    finally:
      - echo "Installed system dependencies"
  # build:
  #   run-as: www-data
  #   on-failure: ABORT
  #   commands:
  #     # - bash ./scripts/install_dependencies.sh
  #     - echo "hello 2"
  #   finally:
  #     - echo "Installed composer dependencies"

artifacts:
  files:
    - '**/*'
  name: prod-manager-builded-$(date +%Y-%m-%d)
  discard-paths: no
  base-directory: /
  enable-symlinks: yes
